"""add_split_sweep_columns

Revision ID: 048ae6d05c91
Revises: b19483168dd1
Create Date: 2026-06-25 14:44:11.677479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048ae6d05c91'
down_revision: Union[str, None] = 'b19483168dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'invoices', 'merchants', ['merchant_id'], ['id'])
    op.add_column('merchants', sa.Column('sweep_cold_address', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('sweep_split_ratio', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'webhook_deliveries', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_deliveries', type_='foreignkey')
    op.drop_column('merchants', 'sweep_split_ratio')
    op.drop_column('merchants', 'sweep_cold_address')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    # ### end Alembic commands ###
