"""Add sweep columns

Revision ID: b19483168dd1
Revises: e86d7e8cd83a
Create Date: 2026-06-25 14:15:57.401081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19483168dd1'
down_revision: Union[str, None] = 'e86d7e8cd83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_swept', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'invoices', 'merchants', ['merchant_id'], ['id'])
    op.add_column('merchants', sa.Column('sweep_address', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('sweep_threshold', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'webhook_deliveries', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_deliveries', type_='foreignkey')
    op.drop_column('merchants', 'sweep_threshold')
    op.drop_column('merchants', 'sweep_address')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'is_swept')
    # ### end Alembic commands ###
