"""Add xpub columns and webhook_deliveries

Revision ID: e86d7e8cd83a
Revises: db4ad057f026
Create Date: 2026-06-25 14:04:33.007573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86d7e8cd83a'
down_revision: Union[str, None] = 'db4ad057f026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'invoices', 'merchants', ['merchant_id'], ['id'])
    op.add_column('merchants', sa.Column('xpub', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('next_address_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'next_address_index')
    op.drop_column('merchants', 'xpub')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_table('webhook_deliveries')
    # ### end Alembic commands ###
